import Head from 'next/head'
import React, { Dispatch, useContext, useEffect } from 'react'
import { MainContext } from '../../context/context';
import UserLayout from '../../layouts/userLayout';
import instance from '../../configs/axios';
import FavouriteProducts from '../../components/favouriteProducts';
import { Empty } from 'antd';

const Favourites = () => {
    const {setLikedProducts,likedProducts,}: { setLikedProducts: Dispatch<number[]>; likedProducts: number[] } =useContext(MainContext);
    const fetchData = async() => {
        try {
            const res = await instance({
                url: "/api/site/get-all-products",
                method: "GET",
            })
            console.log(res?.data)
        } catch (error) {
            
        }
    }
    useEffect(() => {
        fetchData()
    },[])
  return (
    <div>
         <Head>
        <title>Marketplace Favourites</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {likedProducts ? (

        <FavouriteProducts/>
      ): (
        <Empty description={false} />
      )}
    </div>
  )
}

export default Favourites
Favourites.layout = UserLayout
