import Head from 'next/head'
import styles from '../styles/Home.module.css'
import UserLayout from '../layouts/userLayout';
import Hero from '../components/hero';
import CategoryListForHome from '../components/categoryList/categoryListForHome';
import ProductCard from '../components/product/productCard';
import instance from '../configs/axios';
import { useEffect, useState } from 'react';


export default function Home() {
  const [allProducts,setAllProducts] = useState([])
  const fetchData = async() => {
  try {
    const res = await instance({
      url:"/api/site/get-all-products",
      method: "GET"
    })
    setAllProducts(res?.data)
  } catch (error) {
    
  }
  }
  useEffect(()=>{
    fetchData()
  },[])
  
  return (
    <div className='px-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero/>
      <CategoryListForHome/>
      <ProductCard data={allProducts}/>
    </div>
  )
}
Home.layout=UserLayout
